[package]
name = "gee"
version = "0.1.0"
authors = ["Jake Brownson <jake@brainiumstudios.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.6"

[dependencies.euclid]
version = "0.19.5"
optional = true

[dependencies.serde]
version = "1.0.84"
features = ["serde_derive"]
optional = true