[package]
name = "gee"
version = "0.1.0"
authors = ["Jake Brownson <jake@brainiumstudios.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.6"
serde = {version = "1.0.84", optional = true}
serde_derive = {version = "1.0.84", optional = true}

[features]
default = []
serde_support = ["serde", "serde_derive"]