[package]
name = "gee"
version = "0.1.0"
description = "A simple geometry library intended for 2d games"
authors = ["Jake Brownson <jake@brainiumstudios.com>"]
edition = "2018"
repository = "https://github.com/BrainiumLLC/gee"
license = "MIT"
keywords = ["geometry", "games"]
categories = ["games", "graphics", "science"]

[features]
default = []

[dependencies]
en = { git = "https://github.com/BrainiumLLC/en" }
serde = { version = "1.0.106", features = ["serde_derive"], optional = true }
strum = "0.18.0"
strum_macros = "0.18.0"
