[package]
name = "gee"
version = "0.1.0"
description = "A simple geometry library intended for 2d games"
authors = ["Jake Brownson <jake@brainiumstudios.com>"]
edition = "2018"
repository = "https://github.com/BrainiumLLC/gee"
license = "MIT"
keywords = ["geometry", "games"]
categories = ["games", "graphics", "science"]

[dependencies]
num-traits = "0.2.6"
strum = "0.13.0"
strum_macros = "0.13.0"

[dependencies.euclid]
version = "0.19.5"
optional = true

[dependencies.serde]
version = "1.0.84"
features = ["serde_derive"]
optional = true