unstable_features = true
format_strings = true
comment_width = 100
max_width = 100
merge_imports=true
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
struct_field_align_threshold = 100
wrap_comments = true
edition = "2018"